name: Update TwitchPlus

on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main

      - name: Download TwitchPlus.ipa
        run: |
          JSON=$(curl -s "https://api.github.com/repos/YTLitePlus/YTLitePlus/releases/latest")
          URL=$(echo "$JSON" | jq -r '.assets[] | select(.name | contains("YTLitePlus")) | .browser_download_url')
          if [ -z "$URL" ] || [ "$URL" == "null" ]; then
            exit 1
          fi
          curl -L -o ./YTLitePlus.ipa "$URL"

      - name: Delete old release
        run: |
          JSON=$(curl -sH "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" https://api.github.com/repos/EscapeAltDelete/TwitchUpdater/releases/tags/TwitchPlus)
          RID=$(echo $JSON | jq -r '.id')
          curl -X DELETE -H 'Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}' https://api.github.com/repos/EscapeAltDelete/TwitchUpdater/releases/$RID &
          DELETE_PID=$!
          wait $DOWNLOAD_PID $DELETE_PID

      - name: Release TwitchPlus
        uses: ncipollo/release-action@main
        with:
          tag: TwitchPlus
          name: TwitchPlus
          body: "Latest release of TwitchPlus"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifacts: "./TwitchPlus.ipa"
