name: Update TwitchPlus
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: swaggyP36000/TrollStore-IPAs
          regex: true
          file: ".*TwitchPlus.*"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - run: |
          FILE_NAME=$(ls | grep 'TwitchPlus.*')
          JSON=$(curl -sH "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" https://api.github.com/repos/EscapeAltDelete/TwitchUpdater/releases/tags/TwitchPlus)
          RID=$(echo $JSON | jq -r '.id')
          curl -X DELETE -H 'Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}' https://api.github.com/repos/EscapeAltDelete/TwitchUpdater/releases/$RID &
          DELETE_PID=$!
          wait $DELETE_PID
      - uses: ncipollo/release-action@main
        with:
          tag: TwitchPlus
          name: TwitchPlus
          body: "Latest release of TwitchPlus"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifacts: TwitchPlus.ipa
