name: Update TwitchPlus
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: |
          JSON=$(curl -s "https://api.github.com/repos/swaggyP36000/TrollStore-IPAs/releases/latest")
          ASSETS=$(echo $JSON | jq -r '.assets[]')
          for ASSET in $ASSETS
          do
            ASSET_NAME=$(echo $ASSET | jq -r '.name')
            if [[ $ASSET_NAME == *"TwitchPlus"* ]]; then
              URL=$(echo $ASSET | jq -r '.browser_download_url')
              if curl --output /dev/null --silent --head --fail "$URL"; then
                curl -L -o ./TwitchPlus.ipa $URL &
                DOWNLOAD_PID=$!
              fi
            fi
          done
          JSON=$(curl -sH "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" https://api.github.com/repos/EscapeAltDelete/TwitchUpdater/releases/tags/TwitchPlus)
          RID=$(echo $JSON | jq -r '.id')
          curl -X DELETE -H 'Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}' https://api.github.com/repos/EscapeAltDelete/TwitchUpdater/releases/$RID &
          DELETE_PID=$!
          wait $DOWNLOAD_PID $DELETE_PID
      - uses: ncipollo/release-action@main
        with:
          tag: TwitchPlus
          name: TwitchPlus
          body: "Latest release of TwitchPlus"
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          artifacts: "./TwitchPlus.ipa"
